// This file has been generated by teseract, but can be modified as long as the
// section between comments GENERATED and END GENERATED (including the comments)
// is not removed

// GENERATED teseract definitions
declare module "*.jpg" {
  const content: string;
  export default content;
}
declare module "*.jpeg" {
  const content: string;
  export default content;
}
declare module "*.png" {
  const content: string;
  export default content;
}
declare module "*.gif" {
  const content: string;
  export default content;
}
declare module "*.svg" {
  const content: string;
  export default content;
}
declare module "*.ttf" {
  const content: string;
  export default content;
}
// END GENERATED teseract definitions